name: Docker Image CI

on:
  push:
    branches: 
    - main
    - v**

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [backend]
        language: [-node, -dotnet]
        include:
        - component: frontend
          language: 


    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve short sha
      run: |
        echo "GITHUB_SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
        echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
    
    - name: Print env
      run: env | sort 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build the ${{ matrix.docker_context }} Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ${{ matrix.component }}/${{ matrix.language }}
        file: ${{ matrix.component }}/${{ matrix.language }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spm-${{ matrix.component }}:${{ env.BRANCH_NAME }}-${{ env.GITHUB_SHORT_SHA }}${{ matrix.language }},|
              ${{ secrets.DOCKERHUB_USERNAME }}/spm-${{ matrix.component }}:${{ env.BRANCH_NAME }}${{ matrix.language }}