name: Docker Image CI

on:
  push:
    branches: 
    - main
    - releases/**

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - docker_context: frontend
          docker_image_name: spm-frontend
          docker_image_tag: main-$(git rev-parse --short "$GITHUB_SHA")

        - docker_context: backend/node
          docker_image_name: spm-backend
          docker_image_tag: main-$(git rev-parse --short "$GITHUB_SHA")-node

        - docker_context: backend/dotnet
          docker_image_name: spm-backend
          docker_image_tag: main-$(git rev-parse --short "$GITHUB_SHA")-dotnet

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build the ${{ matrix.docker_context }} Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ${{ matrix.docker_context }}
        file: ${{ matrix.docker_context }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.docker_image_name }}:${{ matrix.docker_image_tag }}